ignores:
  - "@commitlint/config-conventional"
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/parser"
  - autoprefixer
  - commitlint
  - concurrently
  - eslint-config-prettier
  - eslint-plugin-cypress
  - eslint-plugin-jsonc
  - eslint-plugin-jsx-a11y
  - eslint-plugin-prettier
  - eslint-plugin-react
  - eslint-plugin-react-hooks
  - eslint-plugin-tailwindcss
  - git-cz
  - html-webpack-plugin
  - jsonc-eslint-parser
  - lint-staged
  - next
  - npm-package-json-lint-config-default
  - prettier-plugin-packagejson
  - prettier-plugin-solidity
  - prettier-plugin-sort-json
  - prettier-plugin-tailwindcss
  - rimraf
  - shx
  - tsconfig-paths-webpack-plugin
  - tsup
  - typescript
  - vercel
  - webpack-dev-server
