ignores:
  - "@commitlint/config-conventional"
  - "@ethersproject/abi"
  - "@ethersproject/providers"
  - "@lightdotso/jest"
  - "@lightdotso/tsconfig"
  - "@matterlabs/hardhat-zksync-solc"
  - "@nomiclabs/hardhat-ethers"
  - "@nomiclabs/hardhat-etherscan"
  - "@nomiclabs/hardhat-waffle"
  - "@openzeppelin/hardhat-upgrades"
  - "@release-it/keep-a-changelog"
  - "@types/chai"
  - "@types/jest"
  - "@types/mocha"
  - "@types/node"
  - "@typechain/ethers-v5"
  - "@typechain/hardhat"
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/parser"
  - autoprefixer
  - commitlint
  - concurrently
  - cross-env
  - dotenv
  - eslint-config-prettier
  - eslint-config-turbo
  - eslint-plugin-cypress
  - eslint-plugin-jsonc
  - eslint-plugin-jsx-a11y
  - eslint-plugin-prettier
  - eslint-plugin-react
  - eslint-plugin-react-hooks
  - eslint-plugin-tailwindcss
  - ethereum-waffle
  - git-cz
  - hardhat
  - hardhat-abi-exporter
  - hardhat-deploy
  - hardhat-gas-reporter
  - hardhat-preprocessor
  - hardhat-watcher
  - html-webpack-plugin
  - jsonc-eslint-parser
  - lint-staged
  - next
  - npm-package-json-lint-config-default
  - prettier-plugin-packagejson
  - prettier-plugin-solidity
  - prettier-plugin-sort-json
  - prettier-plugin-tailwindcss
  - release-it
  - rimraf
  - solc
  - shx
  - toml
  - tsconfig-paths
  - tsconfig-paths-webpack-plugin
  - tsup
  - typechain
  - typescript
  - vercel
  - webpack-dev-server
