ignores:
  - "@lightdotso/changelog"
  - "@lightdotso/styles"
  - "@lightdotso/tsconfig"
  - "@tailwindcss/*"
  - "@types/jest"
  - babel-plugin-istanbul
  - critters
  - jest-environment-jsdom
  - next-themes
  - nyc
  - start-server-and-test
