ignores:
  - "@lightdotso/ens"
  - "@lightdotso/protocol"
  - "@lightdotso/proxies"
  - "@lightdotso/renderer"
  - "@lightdotso/typechain"
  - "@lightdotso/upgradeable"
  - "@lightdotso/tsconfig"
  - "@openzeppelin/contracts"
  - "@openzeppelin/contracts-upgradeable"
  - solc
  - ts-node
