ignores:
  - "@ethersproject/abi"
  - "@ethersproject/providers"
  - "@lightdotso/hardhat-config"
  - "@lightdotso/typechain"
  - "@lightdotso/tsconfig"
  - "@nomiclabs/hardhat-ethers"
  - "@nomiclabs/hardhat-etherscan"
  - "@nomiclabs/hardhat-waffle"
  - "@openzeppelin/hardhat-upgrades"
  - "@typechain/ethers-v5"
  - "@typechain/hardhat"
  - dotenv
  - ethers
  - ethereum-waffle
  - hardhat-abi-exporter
  - hardhat-deploy
  - hardhat-gas-reporter
  - hardhat-preprocessor
  - hardhat-watcher
  - solc
  - toml
  - tsconfig-paths
  - ts-node
  - typechain
