name: Pnpm
description: "Pnpm workflow composite"
inputs:
  token:
    description: "Github token secret"
    required: true
runs:
  using: "composite"
  steps:
    - if: github.event_name == 'push'
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.token }}
    - if: github.event_name == 'pull_request'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ inputs.token }}
    - id: nvm
      run: |
        echo ::set-output name=NVMRC::$(cat .nvmrc)
      shell: bash
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/.pnpm-store
        key: |
          pnpm-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-
    - uses: pnpm/action-setup@v2
      with:
        run_install: true
