name: Pnpm
description: "Pnpm workflow composite"
inputs:
  token:
    description: "Github token secret"
    required: true
runs:
  using: "composite"
  steps:
    - if: github.event_name == 'push'
      uses: actions/checkout@v3
      with:
        repository: LightDotSo/LightDotSo
        token: ${{ inputs.token }}
    - if: github.event_name == 'pull_request'
      uses: actions/checkout@v3
      with:
        repository: LightDotSo/LightDotSo
        token: ${{ inputs.token }}
    - id: nvm
      shell: bash
      run: |
        echo ::set-output name=NVMRC::$(cat .nvmrc)
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}
    - uses: actions/cache@v2
      with:
        path: |
          ~/.pnpm-store
        key: |
          pnpm-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-
    - uses: pnpm/action-setup@v2
      with:
        run_install: false
        version: 7.5.0
    - if: ${{ github.repository }} == 'LightDotSo/LightDotSo'
      shell: bash
      run: |
        pnpm install
    - if: ${{ github.repository }} != 'LightDotSo/LightDotSo'
      shell: bash
      run: |
        pnpm install --fix-lockfile
