name: Pnpm
description: "Pnpm workflow composite"
inputs:
  token:
    description: "Github token secret"
    required: true
runs:
  using: "composite"
  steps:
    - if: github.event_name == 'push'
      uses: actions/checkout@v3
      with:
        repository: LightDotSo/LightDotSo
        token: ${{ inputs.token }}
    - if: github.event_name == 'pull_request'
      uses: actions/checkout@v3
      with:
        repository: LightDotSo/LightDotSo
        token: ${{ inputs.token }}
    - id: nvm
      shell: bash
      run: |
        echo ::set-output name=NVMRC::$(cat .nvmrc)
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}
    - uses: pnpm/action-setup@v2
      with:
        run_install: false
    - if: github.repository == "LightDotSo/LightDotSo"
      shell: bash
      run: |
        pnpm install --frozen-lockfile
    - if: github.repository != "LightDotSo/LightDotSo"
      shell: bash
      run: |
        pnpm install --no-lockfile
