name: Check
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: ./.github/actions/pnpm
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - run: |
          pnpm run lint
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      - if: failure()
        run: |
          pnpm run fix
      - uses: stefanzweifel/git-auto-commit-action@v4
