name: Contracts
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  contracts:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          pnpm run build --scope=@lightdotso/contracts --include-dependencies --no-deps
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      - working-directory: packages/contracts
        run: |
          forge test -vvv --gas-report
