name: Foundry
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  forge:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          forge install
          forge test -vvvvv --gas-report
          forge snapshot --check
      - run: |
          forge test --gas-report --fuzz-seed 0 | tee gasreport.ansi
      - id: gas
        uses: Rubilmax/foundry-gas-diff@v3.8
      - if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          delete: ${{ !steps.gas.outputs.markdown }}
          message: ${{ steps.gas.outputs.markdown }}
