name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          forge install
      - run: |
          pnpm run build
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      - uses: changesets/action@v1
        with:
          publish: pnpm release -r
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
