name: Test
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        package: [app]
    steps:
      - uses: actions/checkout@v3
      - id: path
        run: echo "::set-output name=matrix::{\"include\":[{\"app\":\"apps/app\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
      - run: |
          echo ${{ fromJSON(steps.path.outputs.matrix).include[0].matrix.package }}
      # - uses: ./.github/actions/pnpm
      #   with:
      #     token: ${{ secrets.BOT_TOKEN }}
      - run: |
          echo ${{ steps.path.outputs.PATH }}
      - run: |
          pnpx turbo run test --scope=@lightdotso/${{ matrix.package }}
        continue-on-error: true
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          working-directory: ${{ steps.path.outputs.PATH }}
